name: build pi zero w
on:
  push:

jobs:

  create_image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    
    - name: Define the image name
      id: image_and_branch_name
      run: |
        if [ ${GITHUB_REF/refs\/tags\//} != ${GITHUB_REF} ]; then
          echo ::set-output name=LOCAL_BRANCH::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=IMAGE_NAME_SUFFIX::${GITHUB_REF/refs\/tags\//}
        elif [ ${GITHUB_REF/refs\/heads\//} = "main" ]; then
          echo ::set-output name=LOCAL_BRANCH::main
          echo ::set-output name=IMAGE_NAME_SUFFIX::latest
        fi

    - name: Create a release image using chroot
      uses: pguyot/arm-runner-action@v1
      id: arm_runner_install
      with:
        image_additional_mb: 3584
        base_image: 'raspios_lite:2021-03-04'
        copy_repository_path: /home/pi/pi-0-w
        cpu: 'arm1176'
        commands: |
            echo GITHUB_BRANCH=${{ steps.image_and_branch_name.outputs.LOCAL_BRANCH }}
            echo GITHUB_REPOSITORY=${{ github.repository }}
            sudo GITHUB_BRANCH=${{ steps.image_and_branch_name.outputs.LOCAL_BRANCH }} GITHUB_REPOSITORY=${{ github.repository }} /bin/bash setup
            sudo apt-get autoremove -y
            sudo apt-get clean

    - name: Compress the release image with pishrink
      run: |
        mv ${{ steps.arm_runner_install.outputs.image }} pi-0-w-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img
        wget https://raw.githubusercontent.com/Drewsif/PiShrink/fa3c7a27406e7c0a1c7b8688e330f14a766be1ba/pishrink.sh
        sudo bash pishrink.sh -Z -a -p pi-0-w-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img

    - name: Create release with dev image
      if: github.ref == 'refs/heads/main'
      uses: "marvinpinto/action-automatic-releases@v1.1.2"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        draft: false
        title: "development image"
        files: pi-0-w-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img.xz

    - name: Create release with release image
      if: startsWith(github.ref, 'refs/tags/')
      uses: "marvinpinto/action-automatic-releases@v1.1.2"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: false
        files: pi-0-w-${{ steps.image_and_branch_name.outputs.IMAGE_NAME_SUFFIX }}.img.xz